---
# tasks file for catcm
- name: Namespace for catcm
  community.kubernetes.k8s:
    state: "{{ catcm_state }}"
    name: "{{ catcm_namespace }}"
    api_version: v1
    kind: Namespace

- name: catcm service
  community.kubernetes.k8s:
    state: "{{ catcm_state }}"
    namespace: "{{ catcm_namespace }}"
    template: "{{ item }}"
  with_items:
    - library-core.yml.j2
    - library-web.yml.j2
    - livedata-core.yml.j2
    - livedata-web.yml.j2
    - treatment-core.yml.j2
    - treatment-web.yml.j2
    - ingress.yml.j2
  tags:
    - catcm
